apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-jira-project
  title: Create Jira Project2
spec:
  parameters:
    - title: Jira Project Info
      required:
        - projectKey
        - projectName
        - leadAccountId
      properties:
        projectKey:
          type: string
        projectName:
          type: string
        leadAccountId:
          type: string
  steps:
    - id: createJira
      name: Create Jira Project
      action: custom:jira:create-project
      input:
        projectKey: ${{ parameters.projectKey }}
        projectName: ${{ parameters.projectName }}
        leadAccountId: ${{ parameters.leadAccountId }}
