apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-confluence-pages
  title: Create Confluence Structure3
  description: Generate documentation structure in Confluence
spec:
  owner: your-team
  type: service
  steps:
    - id: callScript
      name: Run Node script
      action: run:script
      input:
        script: |
          node create-confluence-structure.js
